### PR TITLE
Add norwegian bokmål  language

### PR DESCRIPTION
**Pull request by cobraz**
Hello 👋

This pull request adds support for Norwegian (bokmål). Norway has two written languages; _bokmål_ and _nynorsk_. The most common is bokmål. I am not fluent in _nynorsk_, so I have to leave that to anyone who is.

### CODE REVIEW

**Comment by cobraz** [comment]
@LoicMahieu Do you need anything from me?

**Comment by cobraz** [comment]
PS: If someone needs this, I have pre-published it here:
https://github.com/cobraz/yup-locales/packages/122952

**Comment by cobraz** [comment]
@LoicMahieu Would love some feedback! I don't know what to expect. I would rather use this official repository/package than using my own.

**Comment by LoicMahieu** [comment]
Awesome @cobraz 
Thanks and sorry to be late in my response.
I fully trust you with the translations, I don't speak a word of Norwegian ;)

Thanks!

**Comment by LoicMahieu** [comment]
Published:
+ yup-locales@0.4.0

**Comment by cobraz** [comment]
Thanks! 🎉

**Pull request merged**
